#!/bin/bash
IMAGE=registry.guiraudet.com:5000/rpi-snap:latest

DEV='--privileged --volume /dev:/dev'
docker pull $IMAGE
docker run -p 5000:5000 -d --volumes-from data-jupyter $DEV --restart=always --name snap --net robot $IMAGE

