#!/bin/bash
# Execute the tests in a temporary docker container. Delete it afterwards.
#
# /!\ Make sure no other application is running on the GPU otherwise some tests may fail
# due to memory allocation errors.


DIR=${0%${0##*/}}
time docker run $(\ls /usr/lib/x86_64-linux-gnu/libcuda* | xargs -I{} echo '-v {}:{}')   --device /dev/nvidia0:/dev/nvidia0 --device /dev/nvidiactl:/dev/nvidiactl --device /dev/nvidia-uvm:/dev/nvidia-uvm --name test-digits --rm -ti jguiraudet/digits bash /root/test.sh |& tee test-digits.log




